#permalink: /:categories/:year/:month/:day/:title
permalink: pretty
auto: true
pygments: true
markdown: maruku
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
